// Sheen Initializer - Creates .sheen/ directory structure
import * as fs from 'fs/promises';
import * as path from 'path';
import { ProjectContext } from '../utils/types';

export class SheenInitializer {
  private sheenDir: string;

  constructor(private projectContext: ProjectContext) {
    this.sheenDir = path.join(projectContext.rootDir, '.sheen');
  }

  /**
   * Check if .sheen/ directory exists
   */
  async exists(): Promise<boolean> {
    try {
      await fs.access(this.sheenDir);
      return true;
    } catch {
      return false;
    }
  }

  /**
   * Initialize .sheen/ directory with all files
   */
  async initialize(prompt?: string): Promise<void> {
    await fs.mkdir(this.sheenDir, { recursive: true });
    await this.createPlan(prompt || 'General project improvements');
    await this.createContext();
    await this.createConfig();
    await this.createHistory();
  }

  /**
   * Create plan.md from template
   */
  private async createPlan(prompt: string): Promise<void> {
    const template = `# ${this.getProjectName()} - Sheen Plan

## Goal
${prompt}

## Project Context
- **Type**: ${this.projectContext.type}
${this.projectContext.framework ? `- **Framework**: ${this.projectContext.framework}` : ''}
${this.projectContext.language ? `- **Language**: ${this.projectContext.language}` : ''}

## Tasks

### Phase: Discovery
- [ ] Analyze project structure
- [ ] Identify main components
- [ ] Document current state

### Phase: Planning
- [ ] Design solution approach
- [ ] Break down into subtasks
- [ ] Identify dependencies

### Phase: Implementation
- [ ] Implement features
- [ ] Write tests
- [ ] Commit frequently

### Phase: Validation
- [ ] Run all tests
- [ ] Verify acceptance criteria
- [ ] Document completion

## Progress
- **Current Phase**: Discovery
- **Tasks Completed**: 0
- **Tasks Remaining**: TBD
`;

    await fs.writeFile(path.join(this.sheenDir, 'plan.md'), template, 'utf-8');
  }

  /**
   * Create context.md from project detection
   */
  private async createContext(): Promise<void> {
    const template = `# ${this.getProjectName()} - Project Context

## Project Information
- **Type**: ${this.projectContext.type}
${this.projectContext.framework ? `- **Framework**: ${this.projectContext.framework}` : ''}
${this.projectContext.language ? `- **Language**: ${this.projectContext.language}` : ''}
${this.projectContext.packageManager ? `- **Package Manager**: ${this.projectContext.packageManager}` : ''}

## Structure
${this.projectContext.structure.directories.map(d => `- ${d}/`).join('\n')}

${this.projectContext.structure.mainFiles.length > 0 ? `
### Main Files
${this.projectContext.structure.mainFiles.map(f => `- ${f}`).join('\n')}
` : ''}

## Detected Conventions
${this.projectContext.conventions.testFramework ? `- **Testing**: ${this.projectContext.conventions.testFramework}` : ''}
${this.projectContext.conventions.linter ? `- **Linting**: ${this.projectContext.conventions.linter}` : ''}
${this.projectContext.conventions.formatter ? `- **Formatting**: ${this.projectContext.conventions.formatter}` : ''}

${this.projectContext.git ? `
## Git Information
- **Repository**: Initialized
- **Branch**: ${this.projectContext.git.branch || 'unknown'}
${this.projectContext.git.remote ? `- **Remote**: ${this.projectContext.git.remote}` : ''}
- **Uncommitted Changes**: ${this.projectContext.git.hasUncommittedChanges ? 'Yes' : 'No'}
` : '## Git Information\n- **Repository**: Not initialized'}

## Notes
- Auto-generated by Sheen
- Last updated: ${new Date().toISOString()}
`;

    await fs.writeFile(path.join(this.sheenDir, 'context.md'), template, 'utf-8');
  }

  /**
   * Create config.json with project-specific settings
   */
  private async createConfig(): Promise<void> {
    const config = {
      version: '0.1.0',
      autoApprove: false,
      maxIterations: 50,
      tools: ['file', 'git', 'shell'],
      excludePatterns: [
        'node_modules',
        '.git',
        'dist',
        'build',
        'coverage'
      ],
      opencode: {
        streamOutput: true
      }
    };

    await fs.writeFile(
      path.join(this.sheenDir, 'config.json'),
      JSON.stringify(config, null, 2),
      'utf-8'
    );
  }

  /**
   * Create empty history.jsonl file
   */
  private async createHistory(): Promise<void> {
    const initialEntry = {
      timestamp: new Date().toISOString(),
      event: 'init',
      message: 'Sheen initialized',
      phase: 'discovery'
    };

    await fs.writeFile(
      path.join(this.sheenDir, 'history.jsonl'),
      JSON.stringify(initialEntry) + '\n',
      'utf-8'
    );
  }

  /**
   * Get project name from directory
   */
  private getProjectName(): string {
    return path.basename(this.projectContext.rootDir);
  }
}
